---
 - name:  "create souna file"
   hosts: worker1
   tasks:
    - name: "Create a file if it does not exist"
      command: "touch ~/souna ~/saroura"
      args:
         creates: "~/souna"
      register: createif

    - name: "Display the file to make sure its created"
      command: "ls -lrt ~/souna"
      register: displayif
      when: createif is changed

    - debug: var=displayif.stdout

    - name: "Remove the file if it exist"
      command: "rm -rf ~/souna"
      args:
         removes: "~/souna"
      register: supp   
    - name: "verifier souna est supprimé"
      command: "echo 'ficher supprimé'"
      register: removeif
      when:  supp is changed
    - debug: var=removeif.stdout
